---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mangosthree-mysql
spec:
  selector:
    matchLabels:
      app: mangosthree-mysql
  serviceName: mangosthree-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mangosthree-mysql
    spec:
      containers:
      - name: mangosthree-mysql
        image: ssorriaux/mangosthree-database-mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "mangosthree-secret"
              key: "MYSQL_ROOT_PASSWORD"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 30
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mangosthree-mysql
  labels:
    app: mangosthree-mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mangosthree-mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mangosthree-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bWFuZ29z
  LOGIN_DATABASE_INFO: bWFuZ29zdGhyZWUtbXlzcWw7MzMwNjtyb290O21hbmdvcztyZWFsbWQ=
  WORLD_DATABASE_INFO: bWFuZ29zdGhyZWUtbXlzcWw7MzMwNjtyb290O21hbmdvczttYW5nb3Mz
  CHARACTER_DATABASE_INFO: bWFuZ29zdGhyZWUtbXlzcWw7MzMwNjtyb290O21hbmdvcztjaGFyYWN0ZXIz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangosthree-server
  labels:
    app: mangosthree-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangosthree-server
  template:
    metadata:
      labels:
        app: mangosthree-server
    spec:
      containers:
      - name: mangosthree-server
        image: ssorriaux/mangosthree-server:latest
        stdin: true
        tty: true
        env:
        - name: LOGIN_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangosthree-secret"
              key: "LOGIN_DATABASE_INFO"
        - name: WORLD_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangosthree-secret"
              key: "WORLD_DATABASE_INFO"
        - name: CHARACTER_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangosthree-secret"
              key: "CHARACTER_DATABASE_INFO"
        ports:
        - name: "mangos-server"
          containerPort: 8085
        volumeMounts:
        - name: mangos-maps
          mountPath: /etc/mangos/maps
        - name: mangos-vmaps
          mountPath: /etc/mangos/vmaps
        - name: mangos-mmaps
          mountPath: /etc/mangos/mmaps
        - name: mangos-dbc
          mountPath: /etc/mangos/dbc
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mangos-maps
        hostPath:
          path: /tmp
      - name: mangos-vmaps
        hostPath:
          path: /tmp
      - name: mangos-mmaps
        hostPath:
          path: /tmp
      - name: mangos-dbc
        hostPath:
          path: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: mangosthree-server
  labels:
    app: mangosthree-server
spec:
  ports:
  - name: mangos-server
    port: 8085
  clusterIP: None
  selector:
    app: mangosthree-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangosthree-realmd
  labels:
    app: mangosthree-realmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangosthree-realmd
  template:
    metadata:
      labels:
        app: mangosthree-realmd
    spec:
      containers:
      - name: mangosthree-realmd
        image: ssorriaux/mangosthree-realmd:latest
        env:
        - name: LOGIN_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangosthree-secret"
              key: "LOGIN_DATABASE_INFO"
        ports:
        - name: "mangos-realmd"
          containerPort: 3724
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 3724
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3724
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mangosthree-realmd
  labels:
    app: mangosthree-realmd
spec:
  ports:
  - name: mangos-realmd
    port: 3724
  clusterIP: None
  selector:
    app: mangosthree-realmd
