---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mangoszero-mysql
spec:
  selector:
    matchLabels:
      app: mangoszero-mysql
  serviceName: mangoszero-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mangoszero-mysql
    spec:
      containers:
      - name: mangoszero-mysql
        image: ssorriaux/mangoszero-database-mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "mangoszero-secret"
              key: "MYSQL_ROOT_PASSWORD"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 30
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mangoszero-mysql
  labels:
    app: mangoszero-mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mangoszero-mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mangoszero-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bWFuZ29z
  LOGIN_DATABASE_INFO: bWFuZ29zemVyby1teXNxbDszMzA2O3Jvb3Q7bWFuZ29zO3JlYWxtZA==
  WORLD_DATABASE_INFO: bWFuZ29zemVyby1teXNxbDszMzA2O3Jvb3Q7bWFuZ29zO21hbmdvczA=
  CHARACTER_DATABASE_INFO: bWFuZ29zemVyby1teXNxbDszMzA2O3Jvb3Q7bWFuZ29zO2NoYXJhY3RlcjA=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangoszero-server
  labels:
    app: mangoszero-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangoszero-server
  template:
    metadata:
      labels:
        app: mangoszero-server
    spec:
      containers:
      - name: mangoszero-server
        image: ssorriaux/mangoszero-server:latest
        stdin: true
        tty: true
        env:
        - name: LOGIN_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangoszero-secret"
              key: "LOGIN_DATABASE_INFO"
        - name: WORLD_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangoszero-secret"
              key: "WORLD_DATABASE_INFO"
        - name: CHARACTER_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangoszero-secret"
              key: "CHARACTER_DATABASE_INFO"
        ports:
        - name: "mangos-server"
          containerPort: 8085
        volumeMounts:
        - name: mangos-maps
          mountPath: /etc/mangos/maps
        - name: mangos-vmaps
          mountPath: /etc/mangos/vmaps
        - name: mangos-mmaps
          mountPath: /etc/mangos/mmaps
        - name: mangos-dbc
          mountPath: /etc/mangos/dbc
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mangos-maps
        hostPath:
          path: /tmp
      - name: mangos-vmaps
        hostPath:
          path: /tmp
      - name: mangos-mmaps
        hostPath:
          path: /tmp
      - name: mangos-dbc
        hostPath:
          path: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: mangoszero-server
  labels:
    app: mangoszero-server
spec:
  ports:
  - name: mangos-server
    port: 8085
  clusterIP: None
  selector:
    app: mangoszero-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangoszero-realmd
  labels:
    app: mangoszero-realmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangoszero-realmd
  template:
    metadata:
      labels:
        app: mangoszero-realmd
    spec:
      containers:
      - name: mangoszero-realmd
        image: ssorriaux/mangoszero-realmd:latest
        env:
        - name: LOGIN_DATABASE_INFO
          valueFrom:
            secretKeyRef:
              name: "mangoszero-secret"
              key: "LOGIN_DATABASE_INFO"
        ports:
        - name: "mangos-realmd"
          containerPort: 3724
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 3724
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3724
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mangoszero-realmd
  labels:
    app: mangoszero-realmd
spec:
  ports:
  - name: mangos-realmd
    port: 3724
  clusterIP: None
  selector:
    app: mangoszero-realmd
